config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :home, only: [:index]
  get '/orders', to:'home#orders'
  get '/search', to: "home#search"
  resources :hotels ,except: %i(edit new) do
    scope module: :hotels do
      resources :dishes, only: [:index]
      resources :order_items, only: [:index]
      get '/summary/', to: "order_items#summary"
      resources :orders, only: [:index,:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/data_parsing.rb
require 'csv'

class DataParsing
  def initialize
  end

  def csv_file_path
    @csv_file_path ||= File.read("/Users/rohitgopinath/Downloads/chennai.csv")
  end

  def table
    CSV.parse(csv_file_path, headers: true, skip_blanks: true)
  end

  def import_data
    table.each do |row|
      next unless [row["Name of Restaurant"], row["Address"], row['Location'], row['Dining Rating'], row['Dining Rating Count'], row['Delivery Rating'], row['Delivery Rating Count']].all?
      hotel = Hotel.create(
        name:                  row["Name of Restaurant"],
        address:               row["Address"],
        location:              row['Location'],
        dining_rating:         row['Dining Rating'],
        dining_rating_count:   row['Dining Rating Count'],
        delivery_rating:       row['Delivery Rating'],
        delivery_rating_count: row['Delivery Rating Count'],
        cuisine:               YAML.load(row['Cuisine'])
      )
      next if YAML.load(row['Top Dishes']) == "Invalid"
      YAML.load(row['Top Dishes']).each do |dish|
        hotel.dishes.create(name: dish, price: (50..400).to_a.sample)
      end
    end
  end
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :hotel,inverse_of: :dishes
  has_many :order_items,inverse_of: :dish
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :dishes, class_name: 'Dish', inverse_of: :hotel
  has_many :orders, class_name: 'Order', inverse_of: :hotel
  has_one_attached :profile_picture
  has_many_attached :ambience

  scope :active, -> do
    joins(:dishes)
      .where.not(dishes: { id: nil })
      .distinct('hotels.id')
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :hotel,inverse_of: :orders
  has_many :order_items,inverse_of: :order
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order,inverse_of: :order_items
  belongs_to :dish,inverse_of: :order_items

  def unit_price
    if persisted?
      self[:price]
    else
      dish.price
    end
  end
  def total
    unit_price.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def res_blob_path(blob, options = {})
    if Rails.env.production?
      path = Rails.application.routes.url_helpers.rails_blob_path(blob, options.merge(only_path: true))
      host = ApplicationRecord.current_blob_url
      "#{host}#{path}"
    else
      Rails.application.routes.url_helpers.rails_blob_path(blob, options.merge(only_path: true))
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pagy, @hotels = pagy(Hotel.active.order(:name), items: 60, page: params[:page] || 1)
  end

  def search
    @hotels = Hotel.where("name LIKE ?", "%" + params[:search] + "%")
  end

  def orders
    @orders = Order.order(created_at: :desc)
  end

end

app/controllers/hotels/dishes_controller.rb
class Hotels::DishesController < ApplicationController

  def index
    @hotel  = Hotel.find_by_id params[:hotel_id]
    @dishes = @hotel.dishes.all
  end


end

app/controllers/hotels/order_items_controller.rb
class Hotels::OrderItemsController < ApplicationController

  def index
    @order = Order.find_by_id params[:order_id]
    @item =@order.order_items.all
  end


  def summary
    @hotel = Hotel.find_by_id params[:hotel_id]
    @dishes  = @hotel.dishes.where(id: params[:ids])
  end

end

app/controllers/hotels/orders_controller.rb
class Hotels::OrdersController < ApplicationController

  def index
    @order=Orders.order(created_at: :desc)
  end


  def create
    @hotel=Hotel.find_by_id params[:hotel_id]
    @order = @hotel.orders.create(params.permit(:name,:contact,:total))
    @dishes =@hotel.dishes.where(id: params[:dish_ids])
    @dishes.each do |t|
      t.order_items.create(order:@order)
    end
  end


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/home/index.html.erb
<%= link_to 'orders', orders_path %>

<div class="pagination-numbers" style="margin-bottom: 1rem;">
  <%= pagy_nav(@pagy).html_safe %>
</div>
<div class="columns is-12 is-multiline is-flex">
  <% @hotels.each do |hotel| %>
    <div class="column is-2 p-3">
      <div class="card has-text-centered" style="height: 290px;">
        <% if hotel.profile_picture.attached? %>
          <div class="navbar-avatar user-avatar" style="background-image: url('<%= axb_blob_path(hotel.profile_picture) %>');background-size: cover;"></div>
        <% end %>
        <a href="/hotels/<%= hotel.id %>/dishes"><h1 style="margin: 3px;font-size: 25px;"><%= hotel.name %></h1></a>
        <h3 style="margin: 1px;"><%= hotel.location %></h3>
        <div class="is-flex is-justify-content-space-between">
          <div class="has-text-centered">
            <h4 style="margin: 0px;">Dining Rating</h4>
            <%= hotel.dining_rating %>
          </div>
          <div class="has-text-centered">
            <h4 style="margin: 0px;">Delivery Rating</h4>
            <%= hotel.delivery_rating %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pagination-numbers" style="margin-bottom: 1rem;">
  <%= pagy_nav(@pagy).html_safe %>
</div>

app/views/home/orders.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
      #order {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
      }

      #order td, #order th {
          border: 1px solid #ddd;
          padding: 8px;
          text-align: center;
      }

      #order tr:nth-child(even) {
          background-color: #f2f2f2;
      }

      #order tr:hover {
          background-color: #ddd;
      }

      #order th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: center;
          background-color: #a3a3a3;
          color: white;
      }
  </style>
</head>
<body>
<%= link_to "Home", "/home" %>
<h1 style="text-align: center;margin:5px 0px;">My orders</h1>
<table id="order">
  <tr>
    <th> Date of order</th>
    <th>Restaurant</th>
    <th>Order value</th>
  </tr>
  <% @orders.each do |t| %>
    <tr>
      <td><%= t.created_at.to_date %></td>
      <td> <%= t.hotel.name %></td>
      <td><%= t.total %></td>
    </tr>
  <% end %>
</table>
</body>
</html>

app/views/home/search.html.erb
<h3>Search results</h3>
<%= link_to "back", root_path %>
<% @hotels.each do |result| %>
  <div style="width:32%;float:left;">
    <a href="/hotels/<%= result.id %>/dishes"><h1 style="margin: 3px;font-size: 25px;"><%= result.name %></h1></a>
    <h3 style="margin: 1px;"><%= result.location %></h3>
    <div style="float:left;width: 50%; ">
      <div style="width:50%;float:left;">
        <h4 style="margin: 0px;">Dining Rating</h4>
        <%= result.dining_rating %>
      </div>
      <div style="width: 50%;float:right;">
        <h4 style="margin: 0px;">Delivery Rating</h4>
        <%= result.delivery_rating %>
      </div>
    </div>
  </div>
<% end %>

app/views/hotels/dishes/index.html.erb
<%= link_to "Home", "/home" %>
<div style="background: #a3a3a3;width: 25%;padding: 0px 6px 10px 6px;">
<h1 style="margin: 0px;"><%= @hotel.name %></h1>
<h2 style="margin: 0px;"><%= @hotel.location %></h2>
<p style="margin: 0px;"><%= @hotel.dining_rating %></p>
<h3 style="margin: 0px 36px;">Our Menu</h3>
<%= form_with url: "/hotels/#{@hotel.id}/summary", method: :get do |f| %>
  <table>
    <tr>
      <th> Item</th>
      <th>Price</th>
    </tr>
    <% @dishes.each do |dish| %>
      <tr>
        <td>
          <%= check_box_tag('ids[]',"#{dish.id}") %>
          <%= label_tag(:name, "#{dish.name}") %>
          </td>
        <td><%= dish.price %></td>
      </tr>
    <% end %>
  </table>
  <%= f.submit "Confirm selection" %>
<% end %>
</div>

app/views/hotels/order_items/summary.html.erb
<%= link_to "Home", "/home" %>
<%= form_with url: "/hotels/#{@hotel.id}/orders", method: :post do |f| %>
  <div style="background: #a3a3a3;width: 25%;padding: 0px 6px 10px 6px;">
<table>
  <h2 style="text-decoration: underline;"><%=@hotel.name%></h2>
  <tr>
    <th> Item</th>
    <th>Price</th>
  </tr>
  <% @dishes.each do |dish| %>
    <tr>
      <td><%= dish.name %></td>
      <td><%= dish.price %></td>
    </tr>
    <%=f.hidden_field 'dish_ids[]', value:dish.id %>
  <% end %>
</table>
  <p>Total:<%= @dishes.sum(:price) %></p>
  <%=f.hidden_field 'total',value:@dishes.sum(:price)%>
  <label for="Name"> Name:</label><br>
  <input type="text" id="name" name="name"><br>
  <label for="contact">Contact:</label><br>
  <input type="text" id="contact" name="contact"><br><br>
  <input type="submit" value="confirm order">
<% end %>
</div>





<%#= order  do |f| %>
<%# @dishes.each do |lkas| %>
<%#=f.hidden_field 'dish_ids[]', value: lkas.id %>
<%# end %>

app/views/hotels/orders/create.html.erb
<%= link_to "Home", "/home" %>
<h1>your order has been placed!</h1>
<table>
  <h2 style="margin: 0px 0px 10px 0px;"><%= @hotel.name %></h2>
  <h3 style="margin: 0px;"><%= @hotel.location %></h3>
  <tr>
    <th> Item</th>
    <th>Price</th>
    <th>Date of order</th>
  </tr>
  <% @dishes.each do |dish| %>
    <tr>
      <td><%= dish.name %></td>
      <td><%= dish.price %></td>
      <td><%= Date.today.to_s %></td>
    </tr>
  <% end %>
</table>
<p>Amount paid:<%= @dishes.sum(:price) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div style="background-color:lightpink;width:100%;">
  <form action="/search">
    <input type="text" name="search" placeholder="search">
    <button type="submit">search</button>
  </form>

</div>
<% if notice %> <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %> <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="card" style="height: 90vh;">
  <%= yield %>
</div>
</body>
</html>